import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";

const RobotoMono = Roboto_Mono({
  weight: ["400", "500", "600"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={RobotoMono.className}>
      <body className="font-mono antialiased text-black p-4 max-w-screen-2xl mx-auto">
        <Header />
        <main>{children}</main>
        <footer className="text-center fixed bottom-2 w-full text-xs">
          <span>© 2024 James Graham</span>
        </footer>
      </body>
    </html>
  );
}
